config/routes.rb
Rails.application.routes.draw do

  root to: 'music_queues#index'

  match '/auth/google_oauth2/callback', to: 'google_sessions#create', via: :all
  match '/auth/rdio/callback', to: 'rdio_sessions#create', via: :all
  match '/auth/failure', to: 'google_sessions#fail', via: :all

  get '/search_track', to: 'search#track'
  post '/down_votes/:track_request_id', to: 'down_votes#create', as: 'down_votes'
  post '/up_votes/:track_request_id', to: 'up_votes#create', as: 'up_votes'
  get '/music_queues/playing', to: 'music_queues#playing'
  get '/music_queues/list', to: 'music_queues#list'
  post '/track_requests/update_playing_position/:id/:position', to: 'track_requests#update'
  post '/music_queues/update_playing_track', to: 'music_queues#update_playing_track'

  resources :rdio_sessions, only: [:create, :destroy]
  resources :google_sessions, only: [:new, :create, :destroy]
  resources :music_queues, only: [:show, :index, :create, :new]
  resources :tracks, only: :create
end

app/models/down_vote.rb
class DownVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :track_request
end

app/models/music_queue.rb
class MusicQueue < ActiveRecord::Base
  has_many :track_requests
  has_many :tracks, through: :track_requests

  def remove_first_track_request
    playing_track_request.delete
    set_playing_track_request
  end

  def sort_track_requests
    track_requests.sort_by { |track_request| track_request.score }.reverse
  end

  def playing_track_request
    TrackRequest.find(playing_track_request_id) if playing_track_request_id
  end

  def playing_track
    playing_track_request.track if playing_track_request_id
  end

  def set_playing_track_request
    self.playing_track_request_id = sort_track_requests.first.id
    self.save
  end

  def playlist
    playlist_requests.map(&:track)
  end

  def playlist_requests
    sort_track_requests.reject{ |t| t == playing_track_request }
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :track_requests
  has_many :music_queues, through: :track_requests
end

app/models/track_request.rb
class TrackRequest < ActiveRecord::Base
  belongs_to :track
  belongs_to :music_queue
  has_many :up_votes
  has_many :down_votes
  before_create :set_score
  before_create :set_playing_position

  def set_score
    self.score = 0
  end

  def set_playing_position
    self.playing_position = "0"
  end
end

app/models/up_vote.rb
class UpVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :track_request
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :up_votes
  has_many :down_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception

  private

  def authenticate_with_google
    redirect_to new_google_session_path unless session[:google_user]
  end
end

app/controllers/down_votes_controller.rb
class DownVotesController < ApplicationController
  include DownVotesHelper

  def create
    if valid_down_vote(track_request)
      VoteProcessingService.new(track_request, current_music_queue, current_google_user).process_down_vote
      unless request.xhr?
        redirect_to music_queue_path(current_music_queue)
      end
    else
      redirect_to music_queue_path(current_music_queue), notice: 'You can only place one -1 vote.'
    end
  end

  private

  def track_request
    TrackRequest.find(params[:track_request_id])
  end
end

app/controllers/google_sessions_controller.rb
class GoogleSessionsController < ApplicationController
  include ApplicationHelper

  def create
    if rocketeer?
      user = User.find_or_create_by(email: google_email)
      session[:google_user] = user.id
      redirect_to root_path
    else
      redirect_to new_google_session_path, notice: 'Access Denied'
    end
  end

  def destroy
    session[:google_user] = nil
    render :new
  end

  private

  def google_email
    request.env['omniauth.auth'] ? request.env['omniauth.auth']['info']['email'] : params['info']['email']
  end
end

app/controllers/music_queues_controller.rb
class MusicQueuesController < ApplicationController
  before_filter :authenticate_with_google

  def index
    @music_queues = MusicQueue.all
    @music_queue = MusicQueue.new
  end

  def show
    @music_queue = MusicQueue.find(params[:id])
    session[:current_music_queue] = @music_queue.id
  end

  def create
    @music_queue = MusicQueue.create(name: params['music_queue']['name'], description: params['music_queue']['description'])
    clear_sessions
    session[:current_music_queue] = @music_queue.id
    redirect_to music_queue_path(@music_queue)
  end

  def list
    render(partial: 'list', locals: {list: current_music_queue.playlist, requests: current_music_queue.playlist_requests}, layout: false)
  end

  def playing
    render(partial: 'playing', locals: {track: current_music_queue.playing_track, track_request: current_music_queue.playing_track_request}, layout: false)
  end

  def update_playing_track
    current_music_queue.remove_first_track_request
  end

  private

  def clear_sessions
    session[:music_queue_name] = nil
    session[:music_queue_description] = nil
  end
end

app/controllers/rdio_sessions_controller.rb
class RdioSessionsController < ApplicationController
  def create
    OauthProcessingService.new(request.env['omniauth.auth']).process_response
    session[:rdio_user] = true
    if current_music_queue
      redirect_to music_queue_path(current_music_queue)
    else
      redirect_to music_queues_path
    end
  end

  def destroy
    session[:rdio_user] = false
    if current_music_queue
      redirect_to music_queue_path(current_music_queue)
    else
      redirect_to music_queues_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def track
    @search_results = MusicPlayingService.new(current_music_queue).search_tracks(params['track_name'])
    render :results
  end
end

app/controllers/track_requests_controller.rb
class TrackRequestsController < ApplicationController
  def update
    track_request.playing_position = params[:position]
    track_request.save
    head :ok
  end

  private

  def track_request
    @track_request ||= TrackRequest.find(params[:id])
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def create
    if current_music_queue
      track = Track.find_or_create_by(track_params)
      TrackRequest.create(track_request_params(track))
      MusicPlayingService.new(current_music_queue).update_playlist
      redirect_to music_queue_path(current_music_queue), notice: "#{params['name']} has been added to the Playlist"
    else
      redirect_to root_path, notice: 'Please select a music queue.'
    end
  end

  private

  def track_params
    { name: params['name'], album: params['album'], artist: params['artist'], key: params['key'], icon: params['icon'], duration: params['duration'] }
  end

  def track_request_params(track)
    { track_id: track.id, music_queue_id: current_music_queue.id }
  end
end

app/controllers/up_votes_controller.rb
class UpVotesController < ApplicationController
  include UpVotesHelper

  def create
    if valid_up_vote(track_request)
      VoteProcessingService.new(track_request, current_music_queue, current_google_user).process_up_vote
      unless request.xhr?
        redirect_to music_queue_path(current_music_queue)
      end
    else
      redirect_to music_queue_path(current_music_queue), notice: 'You can only place one +1 vote.'
    end
  end

  private

  def track_request
    TrackRequest.find(params[:track_request_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_google_user
    User.find(session[:google_user]) if session[:google_user]
  end

  def current_rdio_user?
    session[:rdio_user]
  end

  # TODO refactor to remove unnecessary test code
  def rocketeer?
    email = request.env['omniauth.auth'] ? request.env['omniauth.auth']['info']['email'] : params['info']['email']
    email =~ /@hashrocket.com/
  end

  def current_music_queue
    MusicQueue.find(session[:current_music_queue]) if session[:current_music_queue]
  end

  def number_of_votes_for(track_request)
    track_request.score
  end

  def current_track_position
    (100 * current_music_queue.playing_track_request.playing_position.to_i / current_music_queue.playing_track.duration.to_i).to_i.to_s + '%'
  end
end

app/helpers/down_votes_helper.rb
module DownVotesHelper
  def valid_down_vote(track_request)
    !track_request.down_votes.map(&:user).map(&:email).include?(current_google_user.email)
  end
end

app/helpers/up_votes_helper.rb
module UpVotesHelper
  def valid_up_vote(track_request)
    !track_request.up_votes.map(&:user).map(&:email).include?(current_google_user.email)
  end
end

app/views/down_votes/create.js.erb
$('#playlist').html("<%=j render('music_queues/list', list: current_music_queue.playlist) %>");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PartyQueue
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      .flash= flash[:notice]
    %div
      - if current_google_user
        = link_to 'logout of google', google_session_path(current_google_user.id), method: :delete
      - else
        = link_to 'login to google', "/auth/google_oauth2"
        %div
          You must have a hashrocket email address to access playlists.
    %div
      - if current_rdio_user?
        = link_to 'logout of rdio', rdio_session_path('1'), method: :delete
      - else
        = link_to 'login to rdio', '/auth/rdio'
        %div
          You must be logged in with rdio to create playlists and play tracks.
    = yield

app/views/music_queues/_authenticated_rdio_interface.html.haml
:javascript
  var duration = 1; // track the duration of the currently playing track
  $(document).ready(function() {
      var $api = $('#api'), $rdio = $api.rdio("GBlVMAr3_____3RtczU0NGN4N2s5c2V1eWNneG5rNmQ2dHBhcnR5cXVldWUubG9jYWx0dW5uZWwubWX4sC8ZuJ1CjHvWyhDdNEa3");
      $('#api').bind('ready.rdio', function() {
          $rdio.play($('.playing_track').prop('id'), {initialPosition: $('.playing_track_request_position').prop('id')});
        });
      $('#api').bind('playingTrackChanged.rdio', function(e, playingTrack, sourcePosition) {
        if (playingTrack) {
        duration = playingTrack.duration;
        $('#art').attr('src', playingTrack.icon);
        $('#track').text(playingTrack.name);
        $('#album').text(playingTrack.album);
        $('#artist').text(playingTrack.artist);
        }
        });
      $('#api').bind('positionChanged.rdio', function(e, position) {
        $.post("/track_requests/update_playing_position/" + $('.playing_track_request_id').prop('id') +  "/" + position);
        $('#playlist').load("/music_queues/list/");
        $('#position').css('width', Math.floor(100*position/duration)+'%');
        if (position > (duration - .3)) {
          $.post("/music_queues/update_playing_track", function () {
            $('#playing').load("/music_queues/playing", function() {
              $('#playlist').load("/music_queues/list", function() {
                  $rdio.play($('.playing_track').prop('id'));
              });
            });
          });
        }
        });
      $('#api').bind('playStateChanged.rdio', function(e, playState) {
        if (playState == 0) { // paused
        $('#play').show();
        $('#pause').hide();
        } else {
        $('#play').hide();
        $('#pause').show();
        }
        });
      $('#previous').click(function() { $('#api').rdio().previous(); });
      $('#play').click(function() { $('#api').rdio().play(); });
      $('#pause').click(function() { $('#api').rdio().pause(); });
      $('#next').click(function() { $('#api').rdio().next(); });
  });

app/views/music_queues/_list.html.haml
- list.each_with_index do |track, i|
  %div= image_tag(track.icon)
  %div
    %strong
      Track:
    = track.name
  %div
    %strong
      Album:
    = track.album
  %div
    %strong
      Artist:
    = track.artist

  %div
    %strong
      Number of Votes:
    = number_of_votes_for(requests[i])

  - if valid_up_vote(requests[i])
    %div
      = link_to '+1', up_votes_path(requests[i]), method: :post, remote: true
  - if valid_down_vote(requests[i])
    %div
      = link_to '-1', down_votes_path(requests[i]), method: :post, remote: true

app/views/music_queues/_playing.html.haml
%span{class: 'playing_track', id: "#{track.key}"}
%span{class: 'playing_track_request_id', id: "#{track_request.id}"}
%span{class: 'playing_track_request_position', id: "#{track_request.playing_position}"}

%img#art{:src => "#{track.icon}", :height => "200", :width => "200"}
%div
  %div
    %b Track:
    %span#track
      = track.name
  %div
    %b Album:
    %span#album
      = track.album
  %div
    %b Artist:
    %span#artist
      = track.artist
  %div
    %b Position:
    %span{:style => "display:inline-block;width:200px;border:1px solid black;"}
      %span#position{:style => "width:#{current_track_position};display:inline-block;background-color:#666"} &nbsp;
  -# - if current_rdio_user?
  -#   %div
  -#     %button#previous &lt;&lt;
  -#     %button#play |&gt;
  -#     %button#pause ||
  -#     %button#next &gt;&gt;
-# :javascript
-#   window.rdioTrackInfo = {
-#     playPosition: #{track_request.playing_position},
-#     playingTrackId: #{track_request.id},
-#     playingTrackKey: #{track.key}
-#   }

app/views/music_queues/_unauthenticated_rdio_interface.html.haml
:javascript
  var duration = 1; // track the duration of the currently playing track
  var updatePlaylist = function () {
    $('#playlist').load("/music_queues/list", function() {
      $('#playing').load("/music_queues/playing", function() {
        updatePlaylist();
      });
    });
  };
  $(document).ready(function() {
    updatePlaylist();
  });

app/views/music_queues/index.html.haml
- if current_rdio_user?
  = form_for(@music_queue) do |f|
    %p
      %div
        = f.label :name
        = f.text_field :name

      %div
        = f.label :description
        = f.text_field :description

      = f.submit 'Create Playlist'

%p Join a Playlist

- @music_queues.each do |music_queue|
  %p
    %div= link_to music_queue.name || music_queue.id, music_queue_path(music_queue)
    = music_queue.description

app/views/music_queues/show.html.haml
%span{class: 'music_queue', id: "#{@music_queue.id}"}

= form_tag search_track_path, method: :get do
  = text_field_tag 'track_name'
  = submit_tag 'Search for Tracks'

%h3= "#{@music_queue.name || "Music Queue #{@music_queue.id}"}"
%h5= "Description: #{@music_queue.description}"

- if current_music_queue.playing_track
  #api
  %div{id: 'playing'}
    = render 'music_queues/playing', track: current_music_queue.playing_track, track_request: current_music_queue.playing_track_request

- if current_rdio_user?
  = render 'music_queues/authenticated_rdio_interface'
- else
  = render 'music_queues/unauthenticated_rdio_interface'

- if current_music_queue.playlist
  Tracks in the queue:
  %div{id: 'playlist'}
    = render 'music_queues/list', list: current_music_queue.playlist, requests: current_music_queue.playlist_requests

app/views/search/results.html.haml
-if @search_results
  - @search_results.each do |result|
    %p
      %div
        %strong
          = result['artist']
      %div= result['album']
      %div= link_to result['name'], tracks_path(result), method: :post
- else
  No Search Results

app/views/up_votes/create.js.erb
$('#playlist').html("<%=j render('music_queues/list', list: current_music_queue.playlist) %>");